# Generated by Django 2.2.7 on 2019-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('marks', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
